src/Entity/Resume.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ResumeRepository")
 */
class Resume
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $position;

    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * Many Resumes have Many Companies.
     * @ORM\ManyToMany(targetEntity="Company", mappedBy="resumes")
     */
    private $companies;

    public function __construct()
    {
        $this->companies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function setCreatedAt($created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function setUpdatedAt($updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|CompanyResume[]
     */
    public function getCompanies(): Collection
    {
        return $this->companies;
    }

    public function addCompany(Company $company): self
    {
        if (!$this->companies->contains($company)) {
            $this->companies[] = $company;
        }

        return $this;
    }

    public function removeCompany(Company $company): self
    {
        if ($this->companies->contains($company)) {
            $this->companies->removeElement($company);
        }

        return $this;
    }

}

src/Form/ResumeType.php
<?php

namespace App\Form;

use App\Entity\Resume;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ResumeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('position', TextType::class, ['attr' => ['class' => 'form-control']])
            ->add('text', TextAreaType::class, ['attr' => ['class' => 'form-control', 'rows' => 6]])
            ->add('submit', SubmitType::class, ['attr' => ['class' => 'btn btn-primary']]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Resume::class,
        ]);
    }
}

src/Controller/ResumeController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Entity\CompanyResume;
use App\Entity\Resume;
use App\Form\ResumeType;
use App\Repository\ResumeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;


class ResumeController extends AbstractController
{
    public function index(ResumeRepository $resumeRepository): Response
    {
        $user = $this->get('security.token_storage')->getToken()->getUser();
        return $this->render('resume/index.html.twig', [
            'resumes' => $resumeRepository->findBy(['user_id' => $user->getId()]),
        ]);
    }

    public function new(Request $request): Response
    {
        $resume = new Resume();
        $form = $this->createForm(ResumeType::class, $resume);
        $form->handleRequest($request);
        $user = $this->get('security.token_storage')->getToken()->getUser();

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $resume->setUserId($user->getId());
            $date = new \Datetime();
            $resume->setCreatedAt($date);
            $resume->setUpdatedAt($date);
            $entityManager->persist($resume);
            $entityManager->flush();

            return $this->redirectToRoute('resume_index');
        }

        return $this->render('resume/new.html.twig', [
            'resume' => $resume,
            'form' => $form->createView(),
        ]);
    }

    public function show(Resume $resume): Response
    {
        return $this->render('resume/show.html.twig', [
            'resume' => $resume,
        ]);
    }

    public function edit(Request $request, Resume $resume): Response
    {
        $form = $this->createForm(ResumeType::class, $resume);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $resume->setUpdatedAt(new \DateTime());
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('resume_index');
        }

        return $this->render('resume/edit.html.twig', [
            'resume' => $resume,
            'form' => $form->createView(),
        ]);
    }

    public function delete(Resume $resume)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($resume);
        $em->flush();

        return $this->redirectToRoute('resume_index');
    }

    public function sendResume(Request $request, Company $company)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->get('security.token_storage')->getToken()->getUser();

        $sendResumes = $company->getResumes();
        $resume = $em->getRepository(Resume::class)->findBy(['user_id' => $user->getId()]);
        $notSendResume = [];
        foreach ($resume as $item) {
            if (!in_array($item, $sendResumes->getValues())) {
                $notSendResume[] = $item;
            }
        }

        if ($request->getMethod() == Request::METHOD_POST) {
            $values = $request->request->get('resume');
            $resumeSend = $em->getRepository(Resume::class)->findById($values);

            foreach ($resumeSend as $resume) {
                $company->addResume($resume);
                $this->getDoctrine()->getManager()->flush();
            }
            return $this->redirectToRoute('list_companies');
        }

        return $this->render('resume/send-resume.html.twig', [
            'resumes' => $notSendResume,
            'company' => $company
        ]);
    }

    public function reviewHistory()
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $resumes = $em->getRepository(Resume::class)->findBy(['user_id' => $user->getId()]);
        $history = $em->getRepository(CompanyResume::class)->findBy(['resumeId' => $resumes]);

        $filteredHistory = array();
        foreach ($history as $item) {
            $filteredHistory[$item->getResumeId()][$item->getCompanyId()] = $item;
        }

        return $this->render('resume/review-history.html.twig', [
            'resumes' => $resumes,
            'history' => $filteredHistory
        ]);

    }
}

templates/resume/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/resume/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Resume{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }

        button, .btn-warning {
            margin-top: 20px;
        }
    </style>
    <div class="example-wrapper">
        {{ include('resume/_form.html.twig') }}
        <a class="btn btn-warning" href="{{ path('resume_index') }}">Back to list</a>
    </div>

{% endblock %}

templates/resume/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resume index{% endblock %}

{% block body %}
    <style>
        .table {
            width: 80%;
            margin: 10px auto;
        }

        .container {
            margin: 50px 0 0 135px;
        }
        a.btn-secondary {
            margin-left: 110px;
        }
    </style>

    <div class="container">
        <a class="btn btn-secondary" href="{{ path('create_resume') }}">Create resume</a>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Position</th>
                <th>Text</th>
                <th width="12%">Created at</th>
                <th width="28%">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for resume in resumes %}
            <tr>
                <td>{{ resume.id }}</td>
                <td>{{ resume.position }}</td>
                <td>{{ resume.text|length > 80 ? resume.text|slice(0, 80) ~ '...' : resume.text  }}</td>
                <td>{{ resume.createdAt ? resume.createdAt|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('view_resume', {'resume': resume.id}) }}" class="btn btn-info">View</a>
                    <a href="{{ path('update_resume', {'resume': resume.id}) }}" class="btn btn-primary">Update</a>
                    <a href="{{ path('delete_resume', {'resume': resume.id}) }}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

{% endblock %}

templates/resume/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Resume{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }

        button, .btn-warning {
            margin-top: 20px;
        }
    </style>
<div class="example-wrapper">
    {{ include('resume/_form.html.twig') }}
    <a class="btn btn-warning" href="{{ path('resume_index') }}">Back to list</a>
</div>

{% endblock %}

templates/resume/review-history.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <style>
        .col-8 {
            margin-top: 60px
        }
        button {
            margin-top: 30px;
        }
    </style>

    <div class="container col-8">
        <table class="table">
            <thead>
            <tr>
                <th class="text-center" colspan="4" scope="col">Resume</th>
            </tr>
            <tr>
                <th scope="col">Company</th>
                <th scope="col">Sent at</th>
                <th scope="col">Reaction</th>
            </tr>
            </thead>
            <tbody>
            {% for resume in resumes %}
                <tr>
                    <th class="text-center" colspan="4"><a href="{{ path('view_resume', {'resume': resume.id}) }}">{{ resume.position }}</a></th>
                </tr>
                {% for company in resume.companies %}
                    <tr>
                        <td><a href="{{ path('view_company', {'company': company.id}) }}">{{ company.title }}</a></td>
                        <td>{{ history[resume.id][company.id].sent_at|date('Y-m-d H:i:s') }}</td>
                        <td>{{ history[resume.id][company.id].reaction ? history[resume.id][company.id].reaction : 'Not reviewed' }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>

</div>
{% endblock %}

templates/resume/send-resume.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <style>
        .col-4 {
            margin-top: 60px
        }
        button {
            margin-top: 30px;
        }
    </style>
    <div class="container col-4">
    {% if resumes %}
    <p class="font-weight-bold">Select resume</p>

        <form action="{{ path('send_resume', {'company': company.id}) }}" method="POST" name="send_resume">
    <ul class="list-group list-group-flush">
        {% for resume in resumes %}
        <li class="list-group-item">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" name="resume[]" class="custom-control-input" value="{{ resume.id }}" id="{{ resume.id }}">
                <label class="custom-control-label" for="{{ resume.id }}">{{ resume.position }}</label>
            </div>
        </li>
        {% endfor %}
    </ul>
        <button type="submit" id="send_resume_submit" class="btn btn-primary">Submit</button>
        </form>
        {% else %}
            <p>You have applied to this vacancy by all resumes</p>
        {% endif %}
</div>
{% endblock %}

templates/resume/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resume{% endblock %}

{% block body %}
    <style>
        .container{
            margin-top: 60px;
        }
    </style>
    <div class="container">
        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ resume.id }}</td>
            </tr>
            <tr>
                <th>Position</th>
                <td>{{ resume.position }}</td>
            </tr>
            <tr>
                <th>Text</th>
                <td>{{ resume.text }}</td>
            </tr>
            <tr>
                <th>Created at</th>
                <td>{{ resume.createdAt ? resume.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated at</th>
                <td>{{ resume.updatedAt ? resume.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            </tbody>
        </table>
    </div>

{% endblock %}